### ISSUE TITLE
Console Messages Full of GCE Agent Telemetry Errors

### ISSUE THREAD

**Issue by jeffh-cloudflare** [albertogeniola/terraform-gce-vyos#3]
Hello,

I downloaded the image you posted on 10/07/2022 (vyos-equuleus-gce-image.tar.gz), uploaded it to a Google Storage bucket, created an image, then built an instance using the image.

I've been using the serial console within GCP to perform the initial configuration. I am seeing tons of console messages on the serial console and thought you might want to see what's I'm seeing here.

```
11error#011exporterhelper/queued_retry.go:361#011Exporting failed. Try enabling retry_on_failure config option to retry on retryable errors#011{"error": "failed to export time series to GCM: rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Jan 13 04:38:39 vyos-test-01 otelopscol[2446]: go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
Jan 13 04:38:39 vyos-test-01 otelopscol[2446]: #011/root/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/queued_retry.go:361
Jan 13 04:38:39 vyos-test-01 otelopscol[2446]: go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
Jan 13 04:38:39 vyos-test-01 otelopscol[2446]: #011/root/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/metrics.go:133
Jan 13 04:38:39 vyos-test-01 otelopscol[2446]: go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
Jan 13 04:38:39 vyos-test-01 otelopscol[2446]: #011/root/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/queued_retry.go:206
Jan 13 04:38:39 vyos-test-01 otelopscol[2446]: go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
Jan 13 04:38:39 vyos-test-01 otelopscol[2446]: #011/root/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61
Jan 13 04:38:44 vyos-test-01 OSConfigAgent[726]: 2023-01-13T04:38:44.2540Z OSConfigAgent Error main.go:88: context deadline exceeded
Jan 13 04:38:45 vyos-test-01 systemd[1]: conf_reloader.service: Service RestartSec=30s expired, scheduling restart.
Jan 13 04:38:45 vyos-test-01 systemd[1]: conf_reloader.service: Scheduled restart job, restart counter is at 6.
Jan 13 04:38:45 vyos-test-01 systemd[1]: Stopped VyOs configuration reloader.
Jan 13 04:38:45 vyos-test-01 systemd[1]: Started VyOs configuration reloader.
Jan 13 04:38:45 vyos-test-01 python[4033]: Traceback (most recent call last):
Jan 13 04:38:45 vyos-test-01 python[4033]:   File "/opt/gce_helper/conf_reloader.py", line 7, in <module>
Jan 13 04:38:45 vyos-test-01 python[4033]:     from configuration import configuration
Jan 13 04:38:45 vyos-test-01 python[4033]:   File "/opt/gce_helper/configuration.py", line 55, in <module>
Jan 13 04:38:45 vyos-test-01 python[4033]:     configuration = Configuration.load_from_metadata()
Jan 13 04:38:45 vyos-test-01 python[4033]:   File "/opt/gce_helper/configuration.py", line 42, in load_from_metadata
Jan 13 04:38:45 vyos-test-01 python[4033]:     pubsub_subscription = str(get_metadata(metadata_path="/computeMetadata/v1/instance/attributes/pubsub-subscription", alt="text"))
Jan 13 04:38:45 vyos-test-01 python[4033]:   File "/opt/gce_helper/utils.py", line 36, in get_metadata
Jan 13 04:38:45 vyos-test-01 python[4033]:     raise MetadataException(f"Cannot access metadata: {metadata_path}. Return code: {resp.status_code}")
Jan 13 04:38:45 vyos-test-01 python[4033]: exceptions.MetadataException: Cannot access metadata: /computeMetadata/v1/instance/attributes/pubsub-subscription. Return code: 404
Jan 13 04:38:45 vyos-test-01 systemd[1]: conf_reloader.service: Main process exited, code=exited, status=1/FAILURE
Jan 13 04:38:45 vyos-test-01 systemd[1]: conf_reloader.service: Failed with result 'exit-code'.
Jan 13 04:38:47 vyos-test-01 otelopscol[2446]: 2023-01-13T04:38:47.658Z#011warn#011zapgrpc/zapgrpc.go:191#011[core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
Jan 13 04:38:47 vyos-test-01 otelopscol[2446]:   "Addr": "monitoring.googleapis.com:443",
Jan 13 04:38:47 vyos-test-01 otelopscol[2446]:   "ServerName": "monitoring.googleapis.com:443",
Jan 13 04:38:47 vyos-test-01 otelopscol[2446]:   "Attributes": null,
Jan 13 04:38:47 vyos-test-01 otelopscol[2446]:   "BalancerAttributes": null,
Jan 13 04:38:47 vyos-test-01 otelopscol[2446]:   "Type": 0,
Jan 13 04:38:47 vyos-test-01 otelopscol[2446]:   "Metadata": null
Jan 13 04:38:47 vyos-test-01 otelopscol[2446]: }. Err: connection error: desc = "transport: Error while dialing dial tcp 172.217.12.10:443: i/o timeout"
Jan 13 04:39:15 vyos-test-01 systemd[1]: conf_reloader.service: Service RestartSec=30s expired, scheduling restart.
Jan 13 04:39:15 vyos-test-01 systemd[1]: conf_reloader.service: Scheduled restart job, restart counter is at 7.
Jan 13 04:39:15 vyos-test-01 systemd[1]: Stopped VyOs configuration reloader.
Jan 13 04:39:15 vyos-test-01 systemd[1]: Started VyOs configuration reloader.
Jan 13 04:39:16 vyos-test-01 python[4034]: Traceback (most recent call last):
Jan 13 04:39:16 vyos-test-01 python[4034]:   File "/opt/gce_helper/conf_reloader.py", line 7, in <module>
Jan 13 04:39:16 vyos-test-01 python[4034]:     from configuration import configuration
Jan 13 04:39:16 vyos-test-01 python[4034]:   File "/opt/gce_helper/configuration.py", line 55, in <module>
Jan 13 04:39:16 vyos-test-01 python[4034]:     configuration = Configuration.load_from_metadata()
Jan 13 04:39:16 vyos-test-01 python[4034]:   File "/opt/gce_helper/configuration.py", line 42, in load_from_metadata
Jan 13 04:39:16 vyos-test-01 python[4034]:     pubsub_subscription = str(get_metadata(metadata_path="/computeMetadata/v1/instance/attributes/pubsub-subscription", alt="text"))
Jan 13 04:39:16 vyos-test-01 python[4034]:   File "/opt/gce_helper/utils.py", line 36, in get_metadata
Jan 13 04:39:16 vyos-test-01 python[4034]:     raise MetadataException(f"Cannot access metadata: {metadata_path}. Return code: {resp.status_code}")
Jan 13 04:39:16 vyos-test-01 python[4034]: exceptions.MetadataException: Cannot access metadata: /computeMetadata/v1/instance/attributes/pubsub-subscription. Return code: 404
Jan 13 04:39:16 vyos-test-01 systemd[1]: conf_reloader.service: Main process exited, code=exited, status=1/FAILURE
Jan 13 04:39:16 vyos-test-01 systemd[1]: conf_reloader.service: Failed with result 'exit-code'.
Jan 13 04:39:17 vyos-test-01 otelopscol[2446]: 2023-01-13T04:39:17.365Z#011error#011exporterhelper/queued_retry.go:361#011Exporting failed. Try enabling retry_on_failure config option to retry on retryable errors#011{"error": "failed to export time series to GCM: rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Jan 13 04:39:17 vyos-test-01 otelopscol[2446]: go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
Jan 13 04:39:17 vyos-test-01 otelopscol[2446]: #011/root/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/queued_retry.go:361
Jan 13 04:39:17 vyos-test-01 otelopscol[2446]: go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
Jan 13 04:39:17 vyos-test-01 otelopscol[2446]: #011/root/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/metrics.go:133
Jan 13 04:39:17 vyos-test-01 otelopscol[2446]: go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
Jan 13 04:39:17 vyos-test-01 otelopscol[2446]: #011/root/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/queued_retry.go:206
Jan 13 04:39:17 vyos-test-01 otelopscol[2446]: go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
Jan 13 04:39:17 vyos-test-01 otelopscol[2446]: #011/root/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61
Jan 13 04:39:25 vyos-test-01 otelopscol[2446]: 2023-01-13T04:39:25.364Z#011warn#011zapgrpc/zapgrpc.go:191#011[core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
Jan 13 04:39:25 vyos-test-01 otelopscol[2446]:   "Addr": "monitoring.googleapis.com:443",
Jan 13 04:39:25 vyos-test-01 otelopscol[2446]:   "ServerName": "monitoring.googleapis.com:443",
Jan 13 04:39:25 vyos-test-01 otelopscol[2446]:   "Attributes": null,
Jan 13 04:39:25 vyos-test-01 otelopscol[2446]:   "BalancerAttributes": null,
Jan 13 04:39:25 vyos-test-01 otelopscol[2446]:   "Type": 0,
Jan 13 04:39:25 vyos-test-01 otelopscol[2446]:   "Metadata": null
Jan 13 04:39:25 vyos-test-01 otelopscol[2446]: }. Err: connection error: desc = "transport: Error while dialing dial tcp 172.217.7.106:443: i/o timeout"
Jan 13 04:39:27 vyos-test-01 otelopscol[2446]: 2023-01-13T04:39:27.658Z#011error#011exporterhelper/queued_retry.go:361#011Exporting failed. Try enabling retry_on_failure config option to retry on retryable errors#011{"error": "failed to export time series to GCM: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.217.7.106:443: i/o timeout\""}
Jan 13 04:39:27 vyos-test-01 otelopscol[2446]: go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
Jan 13 04:39:27 vyos-test-01 otelopscol[2446]: #011/root/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/queued_retry.go:361
Jan 13 04:39:27 vyos-test-01 otelopscol[2446]: go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
Jan 13 04:39:27 vyos-test-01 otelopscol[2446]: #011/root/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/metrics.go:133
Jan 13 04:39:27 vyos-test-01 otelopscol[2446]: go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
Jan 13 04:39:27 vyos-test-01 otelopscol[2446]: #011/root/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/queued_retry.go:206
Jan 13 04:39:27 vyos-test-01 otelopscol[2446]: go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
Jan 13 04:39:27 vyos-test-01 otelopscol[2446]: #011/root/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61
Jan 13 04:39:46 vyos-test-01 systemd[1]: conf_reloader.service: Service RestartSec=30s expired, scheduling restart.
Jan 13 04:39:46 vyos-test-01 systemd[1]: conf_reloader.service: Scheduled restart job, restart counter is at 8.
Jan 13 04:39:46 vyos-test-01 systemd[1]: Stopped VyOs configuration reloader.
Jan 13 04:39:46 vyos-test-01 systemd[1]: Started VyOs configuration reloader.
Jan 13 04:39:46 vyos-test-01 python[4035]: Traceback (most recent call last):
Jan 13 04:39:46 vyos-test-01 python[4035]:   File "/opt/gce_helper/conf_reloader.py", line 7, in <module>
Jan 13 04:39:46 vyos-test-01 python[4035]:     from configuration import configuration
Jan 13 04:39:46 vyos-test-01 python[4035]:   File "/opt/gce_helper/configuration.py", line 55, in <module>
Jan 13 04:39:46 vyos-test-01 python[4035]:     configuration = Configuration.load_from_metadata()
Jan 13 04:39:46 vyos-test-01 python[4035]:   File "/opt/gce_helper/configuration.py", line 42, in load_from_metadata
Jan 13 04:39:46 vyos-test-01 python[4035]:     pubsub_subscription = str(get_metadata(metadata_path="/computeMetadata/v1/instance/attributes/pubsub-subscription", alt="text"))
Jan 13 04:39:46 vyos-test-01 python[4035]:   File "/opt/gce_helper/utils.py", line 36, in get_metadata
Jan 13 04:39:46 vyos-test-01 python[4035]:     raise MetadataException(f"Cannot access metadata: {metadata_path}. Return code: {resp.status_code}")
Jan 13 04:39:46 vyos-test-01 python[4035]: exceptions.MetadataException: Cannot access metadata: /computeMetadata/v1/instance/attributes/pubsub-subscription. Return code: 404
Jan 13 04:39:47 vyos-test-01 systemd[1]: conf_reloader.service: Main process exited, code=exited, status=1/FAILURE
Jan 13 04:39:47 vyos-test-01 systemd[1]: conf_reloader.service: Failed with result 'exit-code'.
```

Any thoughts as to what might be causing this?

I'm going to try to repeat the processes in a completely separate GCP environment that I have 100% control over to see if there's something unique to how this GCP environment is provisioned. I will let you know what I find.

**Comment by jeffh-cloudflare** [comment]
This might be my own fault for not reading over the requirements for the APIs that need to be enabled. I will close the issue for now and will open a new one if the issue persists. Sounds like it's time for me to RTFM.

**Comment by albertogeniola** [comment]
I'm glad you solved by reading the DOCs. In case you have any suggestion about how to improve it, just let me know!
